FROM amazoncorretto:11
COPY ./target/workflow-worker-0.0.1-SNAPSHOT-jar-with-dependencies.jar workflow-worker-0.0.1-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","workflow-worker-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]